### ISSUE TITLE
Error on "npm install" while downloading node-sass 3.13.1

### ISSUE THREAD

**Issue by omrifeldbau** [kambi-sportsbook-widgets/widget-build-tools#1]
Hi,

i tried to install this package and i got the following error:

> Downloading binary from https://github.com/sass/node-sass/releases/download/v3.1
> 3.1/win32-x64-57_binding.node
> Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win
> 32-x64-57_binding.node":
> 
> HTTP error 404 Not Found
> 
> therefore, i can't install this package. 
> 
> probably upgrading the version of node-sass will assist here.

thanks,

Omri

**Comment by owain-stratton** [comment]
#2 Fixes this issue
